=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/lwpm.schema.json
{
  "title": "JSON schema for configuring LWPM",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://lnmp.khs1994.com",
  "$comment": "https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "description": "see https://docs.lnmp.khs1994.com/windows/lwpm.html",
  "type": "object",
  "definitions": {
    "architecture": {
      "description": "architecture",
      "default": "amd64",
      "type": "string",
      "enum": [
        "arm",
        "arm64",
        "amd64"
      ]
    },
    "os": {
      "description": "os",
      "default": "windows",
      "type": "string",
      "enum": [
        "linux",
        "windows",
        "darwin"
      ]
    },
    "hash": {
      "type": "object",
      "description": "soft package hash",
      "properties": {
        "sha512": {
          "type": "string",
          "description": "sha512 hash"
        },
        "sha256": {
          "type": "string",
          "description": "sha256 hash"
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "name": {
      "type": "string",
      "description": "soft name"
    },
    "description": {
      "type": "string",
      "description": "soft description"
    },
    "version": {
      "type": "string",
      "description": "soft version",
      "default": "x.y.z"
    },
    "pre-version": {
      "type": "string",
      "description": "soft pre version",
      "default": "x.y.z-alpha.1"
    },
    "url": {
      "description": "soft download url",
      "type": "string"
    },
    "url-mirror": {
      "description": "soft download url mirror",
      "type": "string"
    },
    "pre-url": {
      "description": "soft pre version download url",
      "type": "string"
    },
    "hash-url": {
      "type": "object",
      "description": "hash url",
      "properties": {
        "sha256": {
          "type": "string",
          "description": "sha256 url"
        },
        "sha384": {
          "type": "string",
          "description": "sha384 url"
        },
        "sha512": {
          "type": "string",
          "description": "sha512 url"
        }
      },
      "additionalProperties": false
    },
    "pre-url-mirror": {
      "description": "soft pre version download url mirror",
      "type": "string"
    },
    "homepage": {
      "description": "soft homepage",
      "type": "string"
    },
    "bug": {
      "description": "soft bug report",
      "type": "string"
    },
    "github": {
      "description": "soft github, example: user/repo",
      "type": "string",
      "default": "username/repo"
    },
    "releases": {
      "description": "soft releases pages",
      "type": "string"
    },
    "architecture": {
      "$ref": "#/definitions/architecture"
    },
    "os": {
      "$ref": "#/definitions/os"
    },
    "platform": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "architecture": {
            "$ref": "#/definitions/architecture"
          },
          "os": {
            "$ref": "#/definitions/os"
          },
          "hash": {
            "$ref": "#/definitions/hash"
          }
        },
        "additionalProperties": false
      },
      "uniqueItems": true,
      "minimum": 1
    },
    "scripts": {
      "type": "object",
      "properties": {
        "platform-reqs": {
          "type": [
            "string",
            "array"
          ],
          "description": "if last command echo $false, means not support this platform. e.g. echo $False",
          "default": [
            "if(!$IsWindows){echo $False}"
          ]
        },
        "preinstall": {
          "type": [
            "string",
            "array"
          ],
          "default": [
            "# _cleanup \"$unzipDesc\""
          ]
        },
        "install": {
          "type": [
            "string",
            "array"
          ],
          "default": [
            "# Write-Host \"`nPlease download on this website: \\${releases\\}`n\" -ForegroundColor Green",
            "# _unzip \\$filename \\$unzipDesc",
            "# Copy-item -r -force \"\\$unzipDesc/\" \"\"",
            "# cp \\$env:LWPM_PKG_ROOT\\dist\\file \\dest\\path",
            "# Start-Process -FilePath \\$filename -wait",
            "# _cleanup \"\\$unzipDesc\""
          ]
        },
        "postinstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "preuninstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "uninstall": {
          "type": [
            "string",
            "array"
          ],
          "default": "# _cleanup /soft/path"
        },
        "postuninstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "pruneuninstall": {
          "type": [
            "string",
            "array"
          ]
        },
        "pretest": {
          "type": [
            "string",
            "array"
          ]
        },
        "test": {
          "type": [
            "string",
            "array"
          ],
          "default": [
            "printInfo $(command --version) install success"
          ]
        },
        "posttest": {
          "type": [
            "string",
            "array"
          ]
        },
        "version": {
          "type": [
            "string",
            "array"
          ],
          "description": "how to get version string"
        },
        "get-latest-version": {
          "type": "string",
          "description": "Function Get-LatestVersion(){ }",
          "default": [
            "Function Get-LatestVersion(){ }"
          ]
        },
        "get-version": {
          "type": "string",
          "description": "set arg $VERSION",
          "default": [
            "if($isPre){$VERSION='x.y.z-beta'}else{$VERSION='x.y.z'}"
          ]
        },
        "hash": {
          "type": [
            "string",
            "array"
          ],
          "description": "how to check soft package hash"
        },
        "dist": {
          "type": [
            "string",
            "array"
          ],
          "description": "how to dist files",
          "default": [
            "# _mkdir \\$env:LWPM_PKG_ROOT/dist",
            "# curl -L `",
            "# \\$url `",
            "# -o \\$env:LWPM_PKG_ROOT/dist/\\${env:lwpm_os\\}-\\${env:lwpm_architecture\\}/\\$filename"
          ]
        }
      },
      "additionalProperties": false
    },
    "path": {
      "type": "array",
      "description": "insert path",
      "items": {
        "type": "string"
      },
      "default": [
        "C:\\bin"
      ]
    },
    "unix-path": {
      "type": "array",
      "description": "unix system(e.g. Linux/macOS) PATH, add to ~/.bashrc manual",
      "items": {
        "type": "string"
      },
      "default": [
        "/path/bin"
      ]
    },
    "command": {
      "type": "string",
      "description": "what command this package provide"
    },
    "download-filename": {
      "type": "string",
      "description": "download filename"
    },
    "$comment": {
      "type": [
        "string",
        "array"
      ],
      "description": "Comments from this package"
    }
  },
  "required": [
    "version"
  ],
  "additionalProperties": false
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/idea/lwpm.json
{
  "name": "idea",
  "description": "Manage your tools the easy way",
  "version": "2.6.3.43718",
  "pre-version": "2.6.3.43718",
  "homepage": "https://www.jetbrains.com/",
  "bug": "",
  "github": "",
  "releases": "https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JetBrains/Toolbox",
  "url": "https://download.jetbrains.com/toolbox/jetbrains-toolbox-${VERSION}.$(if($IsWindows){echo exe}else{echo dmg})",
  "command": "${env:APPDATA}\\..\\Local\\JetBrains\\Toolbox\\bin\\jetbrains-toolbox.exe",
  "scripts": {
    "install": [
      "Start-Process -FilePath $filename -wait"
    ],
    "test": "if($IsWindows){get-command ${env:APPDATA}\\..\\Local\\JetBrains\\Toolbox\\bin\\jetbrains-toolbox.exe}",
    "version": [
      "$version = (get-command ${env:APPDATA}\\..\\Local\\JetBrains\\Toolbox\\bin\\jetbrains-toolbox.exe).Version",
      "${version}.trim('.0')"
    ],
    "platform-reqs": [
      "if($IsLinux){echo $False}"
    ],
    "uninstall": "& $env:APPDATA\\..\\Local\\JetBrains\\Toolbox\\bin\\Uninstall.exe"
  },
  "$comment": [
    "https://www.jetbrains.com/toolbox-app/"
  ]
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/php-cgi-spawner/lwpm.json
{
  "architecture": "amd64",
  "bug": "",
  "command": "",
  "description": "",
  "download-filename": "",
  "github": "deemru/php-cgi-spawner",
  "homepage": "",
  "name": "php-cgi-spawner",
  "os": "windows",
  "path": [
    "C:\\php",
    "C:\\php-pre"
  ],
  "pre-url": "",
  "pre-url-mirror": "",
  "pre-version": "1.1.23",
  "releases": "",
  "scripts": {
    "install": [
      "$PHP_PREFIX='C:/php'\n\nif($isPre -eq 1){\n  $PHP_PREFIX=\"${PHP_PREFIX}-pre\"\n}\n\nif (!(Test-Path \"${PHP_PREFIX}/php.exe\")){\n  printError \"Can't found php on [ $PHP_PREFIX ]\"\n\n  exit 1\n}\n\nGet-Process php-cgi-spawner -ErrorAction \"SilentlyContinue\" | out-null\n\nif($?){\n  printError \"php-cgi-spawner is running, please stop php first\"\n\n  exit 1\n}\n\nprintInfo \"Install php-cgi-spawner on $PHP_PREFIX ...\"\ncp $filename $PHP_PREFIX\n"
    ],
    "platform-reqs": [
      "if(!$IsWindows){echo $False}\n"
    ],
    "postinstall": "",
    "posttest": "",
    "postuninstall": "",
    "preinstall": "",
    "pretest": "",
    "preuninstall": "",
    "pruneuninstall": "",
    "test": "",
    "uninstall": "_cleanup C:\\php\\php-cgi-spawner.exe",
    "version": ""
  },
  "url": "https://github.com/deemru/php-cgi-spawner/releases/download/${VERSION}/php-cgi-spawner.exe",
  "url-mirror": "https://${env:GITHUB_MIRROR}/deemru/php-cgi-spawner/releases/download/${VERSION}/php-cgi-spawner.exe",
  "version": "1.1.23"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/composer/lwpm.json
{
  "name": "composer",
  "description": "Dependency Manager for PHP",
  "version": "2.10.3",
  "pre-version": "2.10.3",
  "homepage": "https://getcomposer.org/",
  "bug": "https://github.com/composer/composer/issues",
  "github": "composer/composer",
  "releases": "https://getcomposer.org/download/",
  "url": "https://github.com/composer/composer/releases/download/${VERSION}/composer.phar",
  "url-mirror": "https://mirrors.aliyun.com/composer/composer.phar",
  "command": "composer",
  "download-filename": "composer-${VERSION}.phar",
  "scripts": {
    "version": "(composer --version).split(' ')[2]",
    "install": [
      "if($isWindows){_mkdir \"$env:ProgramData\\ComposerSetup\\bin\\\"}",
      "if($isWindows){Copy-item -r -force \"$env:LWPM_PKG_ROOT\\dist\\composer\"      \"$env:ProgramData\\ComposerSetup\\bin\\\"}",
      "if($isWindows){Copy-item -r -force \"$env:LWPM_PKG_ROOT\\dist\\composer.ps1\"  \"$env:ProgramData\\ComposerSetup\\bin\\\"}",
      "if($isWindows){Copy-item -r -force \"$env:LWPM_PKG_ROOT\\dist\\composer.bat\"  \"$env:ProgramData\\ComposerSetup\\bin\\\"}",
      "if($isWindows){Copy-item -r -force $filename                                   \"$env:ProgramData\\ComposerSetup\\bin\\composer.phar\"}",
      "if(!$IsWindows){sudo install -m755 $filename /usr/local/bin/composer}"
    ],
    "test": [
      "printInfo $(composer --version) install success"
    ],
    "uninstall": [
      "_sudo remove-item -r -force $env:ProgramData\\ComposerSetup"
    ],
    "pruneuninstall": [
      "_cleanup \"$HOME\\AppData\\Roaming\\Composer\"",
      "_cleanup \"$HOME\\AppData\\Local\\Composer\""
    ]
  },
  "path": [
    "$env:ProgramData\\ComposerSetup\\bin\\",
    "$HOME\\AppData\\Roaming\\Composer\\vendor\\bin"
  ]
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/python/lwpm.json
{
  "bug": "",
  "command": "python",
  "description": "Python is a programming language that lets you work quickly and integrate systems more effectively",
  "github": "python/cpython",
  "homepage": "https://www.python.org/",
  "name": "python",
  "path": [
    "${env:ProgramData}\\Python",
    "${env:ProgramData}\\Python\\Scripts"
  ],
  "pre-url": "https://www.python.org/ftp/python/${VERSION}/python-${VERSION}-${env:lwpm_architecture}.exe",
  "pre-url-mirror": "https://repo.huaweicloud.com/python/${VERSION}/python-${VERSION}-${env:lwpm_architecture}.exe",
  "pre-version": "3.13.0",
  "releases": "https://www.python.org/downloads/",
  "scripts": {
    "install": [
      "# https://docs.python.org/3.7/using/windows.html#installing-without-ui\n\nStart-Process $filename -Wait `\n-ArgumentList @( `\n  '/quiet', `\n  'InstallAllUsers=1', `\n  \"DefaultAllUsersTargetDir=${env:ProgramData}\\Python\", `\n  \"DefaultJustForMeTargetDir=${env:ProgramData}\\Python\", `\n  \"TargetDir=${env:ProgramData}\\Python\", `\n  'PrependPath=1', `\n  'Shortcuts=0', `\n  'Include_doc=0', `\n  'Include_pip=1', `\n  'Include_test=0' `\n);"
    ],
    "platform-reqs": "if(!$IsWindows){echo $False}",
    "test": "python --version",
    "version": "($(python --version) -split \" \")[1]"
  },
  "url": "https://www.python.org/ftp/python/${VERSION}/python-${VERSION}-${env:lwpm_architecture}.exe",
  "url-mirror": "https://repo.huaweicloud.com/python/${VERSION}/python-${VERSION}-${env:lwpm_architecture}.exe",
  "version": "3.13.0"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/mpv/lwpm.json
{
  "name": "mpv",
  "description": "Video player based on MPlayer/mplayer2",
  "version": "0.39.0",
  "pre-version": "20250615-git-e8ade13",
  "homepage": "https://mpv.io/",
  "bug": "https://mpv.io/bug-reports/",
  "github": "mpv-player/mpv",
  "releases": "https://github.com/mpv-player/mpv/releases",
  "url": "https://downloads.sourceforge.net/project/mpv-player-windows/release/mpv-${VERSION}-x86_64-v3.7z",
  "pre-url": "https://downloads.sourceforge.net/project/mpv-player-windows/64bit-v3/mpv-x86_64-v3-${VERSION}.7z",
  "path": [
    "$env:ProgramData\\mpv"
  ],
  "command": "mpv",
  "scripts": {
    "install": [
      "# https://sourceforge.net/projects/mpv-player-windows/files/",
      "_mkdir ${env:ProgramData}/mpv",
      "powershell -c \"7z x $filename -aoa -r -o${env:ProgramData}/mpv\"",
      "_ln ${env:ProgramData}\\mpv\\mpv.exe $HOME\\Desktop\\mpv.exe"
    ],
    "version": "# (mpv).split()[1]\n echo ${VERSION}",
    "test": "printInfo mpv $((mpv).split()[1]) install success",
    "uninstall": "_cleanup $env:ProgramData\\mpv"
  }
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/k8s/kubernetes-server/lwpm.json
{
  "name": "kubernetes-server",
  "platform": [
    {
      "architecture": "amd64",
      "os": "linux"
    },
    {
      "architecture": "arm64",
      "os": "linux"
    }
  ],
  "scripts": {
    "platform-reqs": [
      "if(!$IsLinux){echo $False}"
    ],
    "dist": "_mkdir $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}\n\ncurl -L `\n  $url `\n  -o $env:LWPM_PKG_ROOT/dist/${env:lwpm_os}-${env:lwpm_architecture}/$filename\n"
  },
  "url": "https://dl.k8s.io/release/v${VERSION}/kubernetes-server-${env:lwpm_os}-${env:lwpm_architecture}.tar.gz",
  "version": "1.35.0"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/s6/lwpm.json
{
  "name": "s6",
  "platform": [
    {
      "os": "linux",
      "architecture": "amd64"
    }
  ],
  "scripts": {
    "install": "sudo tar -zxf $filename -C /",
    "platform-reqs": "if(!$_IsLinux){echo $false}"
  },
  "url": "https://github.com/just-containers/s6-overlay/releases/download/v${VERSION}/s6-overlay-x86_64.tar.xz",
  "url-mirror": "https://${env:GITHUB_MIRROR}/just-containers/s6-overlay/releases/download/v${VERSION}/s6-overlay-x86_64.tar.xz",
  "version": "3.2.3.2"
}

=== khs1994-docker/lnmp/windows/lnmp-windows-pm-repo/vim/lwpm.json
{
  "name": "vim",
  "description": "Vi IMproved - enhanced vi editor",
  "version": "9.1.1473",
  "pre-version": "9.1.1473",
  "homepage": "https://www.vim.org/",
  "bug": "https://github.com/vim/vim-win32-installer/issues",
  "github": "vim/vim-win32-installer",
  "releases": "https://github.com/vim/vim-win32-installer/releases",
  "url": "https://github.com/vim/vim-win32-installer/releases/download/v${VERSION}/gvim_${VERSION}_x86.exe",
  "url-mirror": "https://${env:GITHUB_MIRROR}/vim/vim-win32-installer/releases/download/v${VERSION}/gvim_${VERSION}_x86.exe",
  "command": "vim",
  "scripts": {
    "platform-reqs": [
      "if(!$IsWindows){echo $False}"
    ],
    "install": [
      "Start-Process -FilePath $filename"
    ],
    "uninstall": [
      "$VERSION_X=(vim --version).split(' ')[4].split('.')[0]",
      "$VERSION_Y=(vim --version).split(' ')[4].split('.')[1]",
      "start-process -wait -path ${env:ProgramFiles(x86)}\\Vim\\vim${VERSION_X}${VERSION_Y}\\uninstall-gui.exe"
    ],
    "test": "printInfo $(vim --version)[0] install success",
    "version": [
      "echo ${VERSION}"
    ]
  }
}
