=== khs1994-docker/lnmp/scripts/docker-image-sync/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "$comment": {
        "type": "string"
      },
      "source": {
        "description": "source",
        "type": "string"
      },
      "dest": {
        "description": "dest",
        "type": "string"
      },
      "registry": {
        "description": "source registry",
        "type": "string"
      },
      "image": {
        "description": "source image",
        "type": "string"
      },
      "ref": {
        "description": "source ref",
        "type": "string"
      },
      "digest": {
        "description": "source digest",
        "type": "string"
      },
      "append": {
        "type": "boolean",
        "default": false
      },
      "platforms": {
        "type": "array",
        "description": "all in one",
        "items": {
          "type": "object",
          "properties": {
            "os": {
              "description": "os",
              "type": "string",
              "enum": [
                "linux",
                "windows"
              ]
            },
            "architecture": {
              "description": "architecture",
              "type": "string",
              "enum": [
                "arm",
                "arm64",
                "amd64"
              ]
            },
            "variant": {
              "description": "variant",
              "type": "string",
              "enum": [
                "v5",
                "v6",
                "v7",
                "v8"
              ]
            },
            "source": {
              "description": "source",
              "type": "string"
            },
            "dest": {
              "description": "dest",
              "type": "string"
            },
            "registry": {
              "description": "source registry",
              "type": "string"
            },
            "image": {
              "description": "source image",
              "type": "string"
            },
            "ref": {
              "description": "source ref",
              "type": "string"
            },
            "digest": {
              "description": "source digest",
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== khs1994-docker/lnmp/dockerfile/sync/docker-image-sync-ghcr-mcr.microsoft.com.json
[
  {
    "source": "powershell:preview-7.6-alpine-3.20",
    "dest": "powershell:preview-7.6-alpine-3.20",
    "registry": "mcr.microsoft.com",
    "image": "powershell",
    "ref": "preview-7.6-alpine-3.20",
    "$comment": "https://hub.docker.com/_/microsoft-powershell",
    "append": true
  },
  {
    "source": "powershell:7.5-alpine-3.20",
    "dest": "powershell:7.5-alpine-3.20",
    "registry": "mcr.microsoft.com",
    "image": "powershell",
    "ref": "7.5-alpine-3.20",
    "$comment": "https://hub.docker.com/_/microsoft-powershell",
    "append": true
  }
]
